// webui/src/lib/components/PluginCodeEditor.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { EditorView, basicSetup } from 'codemirror';
  import { EditorState } from '@codemirror/state';
  import { javascript } from '@codemirror/lang-javascript';
  import { oneDark } from '@codemirror/theme-one-dark';

  interface Props {
    content: string;
    /** 与文件扩展名一致，影响 TS/JS 高亮 */
    typescript?: boolean;
    /** 用户编辑时回调（用于标记未保存） */
    onedit?: () => void;
  }

  let { content = $bindable(''), typescript = false, onedit }: Props = $props();

  let el: HTMLDivElement | undefined;

  onMount(() => {
    if (!el) return;
    const state = EditorState.create({
      doc: content,
      extensions: [
        basicSetup,
        javascript({ typescript }),
        oneDark,
        EditorView.theme({
          '&': {
            height: 'min(70vh, 560px)',
            minHeight: '320px',
            fontSize: '0.8125rem',
            lineHeight: '1.5',
          },
          '.cm-scroller': {
            fontFamily: "ui-monospace, 'Cascadia Code', 'Consolas', monospace",
          },
        }),
        EditorView.lineWrapping,
        EditorView.updateListener.of((e) => {
          if (e.docChanged) {
            content = e.state.doc.toString();
            onedit?.();
          }
        }),
      ],
    });
    const view = new EditorView({ state, parent: el });
    return () => view.destroy();
  });
</script>

<div class="cm-root" bind:this={el}></div>

<style>
  .cm-root {
    width: 100%;
    border-radius: var(--radius-md);
    overflow: hidden;
    background: var(--color-card);
  }
  .cm-root :global(.cm-editor) {
    height: 100%;
    border-radius: inherit;
  }
  .cm-root :global(.cm-editor.cm-focused) {
    outline: none;
    box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--color-primary) 45%, transparent);
  }
</style>

// app/webui-react/src/features/plugins/PluginCodeEditor.tsx
import { useEffect, useRef } from 'react'
import { EditorView, basicSetup } from 'codemirror'
import { EditorState } from '@codemirror/state'
import { javascript } from '@codemirror/lang-javascript'

export function PluginCodeEditor({ content, typescript, onChange }: {
  content: string
  typescript?: boolean
  onChange: (content: string) => void
}) {
  const rootRef = useRef<HTMLDivElement>(null)
  const initialContentRef = useRef(content)
  const onChangeRef = useRef(onChange)
  onChangeRef.current = onChange

  useEffect(() => {
    if (!rootRef.current) return
    const state = EditorState.create({
      doc: initialContentRef.current,
      extensions: [
        basicSetup,
        javascript({ typescript }),
        EditorView.lineWrapping,
        EditorView.theme({
          '&': {
            height: '100%',
            minHeight: '0',
            backgroundColor: 'var(--card)',
            color: 'var(--foreground)',
            fontSize: '0.8125rem',
            lineHeight: '1.5',
          },
          '.cm-scroller': { fontFamily: "ui-monospace, 'Cascadia Code', Consolas, monospace" },
          '.cm-gutters': {
            minWidth: '2.75rem',
            backgroundColor: 'var(--background)',
            color: 'var(--muted-foreground)',
            borderRight: '1px solid var(--border)',
          },
          '.cm-activeLine, .cm-activeLineGutter': {
            backgroundColor: 'color-mix(in srgb, var(--primary) 7%, transparent)',
          },
          '&.cm-focused .cm-cursor': { borderLeftColor: 'var(--foreground)' },
          '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection': {
            backgroundColor: 'color-mix(in srgb, var(--primary) 22%, transparent)',
          },
        }),
        EditorView.updateListener.of(update => {
          if (update.docChanged) onChangeRef.current(update.state.doc.toString())
        }),
      ],
    })
    const view = new EditorView({ state, parent: rootRef.current })
    return () => view.destroy()
  }, [typescript])

  return <div ref={rootRef} className="plugin-code-editor" />
}
